# ch585_evb 板级功能开关
set(MOUSE_ENABLE ON CACHE BOOL "KB" FORCE)
set(NKRO_ENABLE ON CACHE BOOL "KB" FORCE)
set(ENCODER_ENABLE OFF CACHE BOOL "KB" FORCE)
set(ENCODER_MAP_ENABLE OFF CACHE BOOL "KB" FORCE)
set(VIA_ENABLE ON CACHE BOOL "KB" FORCE)
set(VIAL_ENABLE ON CACHE BOOL "KB" FORCE)
set(BOOTMAGIC_ENABLE ON CACHE BOOL "KB" FORCE)
set(GRAVE_ESC_ENABLE OFF CACHE BOOL "KB" FORCE)
set(COMMAND_ENABLE OFF CACHE BOOL "KB" FORCE)

# Vial 高阶功能（界面可直接配置）
set(MACRO_ENABLE ON CACHE BOOL "KB" FORCE)
set(TAP_DANCE_ENABLE ON CACHE BOOL "KB" FORCE)
set(COMBO_ENABLE ON CACHE BOOL "KB" FORCE)
set(KEY_OVERRIDE_ENABLE ON CACHE BOOL "KB" FORCE)
set(REPEAT_KEY_ENABLE ON CACHE BOOL "KB" FORCE)

# QMK 原生功能（代码配置，Vial 可映射按键）
set(ONESHOT_ENABLE ON CACHE BOOL "KB" FORCE)
set(LEADER_ENABLE ON CACHE BOOL "KB" FORCE)
set(SPACECADET_ENABLE ON CACHE BOOL "KB" FORCE)
set(AUTO_SHIFT_ENABLE ON CACHE BOOL "KB" FORCE)
set(CAPS_WORD_ENABLE ON CACHE BOOL "KB" FORCE)
set(SECURE_ENABLE ON CACHE BOOL "KB" FORCE)
set(ACHORDION_ENABLE ON CACHE BOOL "KB" FORCE)
set(SENTENCE_CASE_ENABLE ON CACHE BOOL "KB" FORCE)

# M2 先关闭外设，M4 再开
set(RGBLIGHT_ENABLE OFF CACHE BOOL "KB" FORCE)
set(RGB_MATRIX_ENABLE OFF CACHE BOOL "KB" FORCE)
set(AUXILIARY_RGB_ENABLE OFF CACHE BOOL "KB" FORCE)
set(OLED_ENABLE OFF CACHE BOOL "KB" FORCE)

set(SPLIT_KEYBOARD OFF CACHE BOOL "KB" FORCE)
set(EEPROM_DRIVER "custom" CACHE STRING "KB" FORCE)

# 有线模式
set(USB_ENABLE ON CACHE BOOL "KB" FORCE)
set(BLE_ENABLE ON CACHE BOOL "KB" FORCE)
set(ESB_ENABLE OFF CACHE BOOL "KB" FORCE)
set(ESB_ROLE "keyboard" CACHE STRING "KB")
